import { Montserrat } from "next/font/google";
import styles from "./layout.module.css";
import "./globals.css";
import Navbar from "./components/navbar.js";
import Footer from "./components/Footer.js";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Footer />
        {children}
      </body>
    </html>
  );
}
